services:
  npiapp:
    image: python
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 5755:5755
    volumes:
    # - db1:/app/db
      - "C:/Users/Omzig/Desktop/Personal_Projects/npi-docker:/app"
      - type: bind
        source: C:\sqlite\db
        target: /app/db
    container_name: npiapp

#volumes:
#  db1:
#      driver: azure_file
#      driver_opts:
#        share_name: npifiles
#        storage_account_name: npistorage1